title: Bosque
# description: Bosque Programming Language
# author: Harris Brakmic
logo: /assets/images/bosque_logo_500x500.png
github: https://github.com/microsoft/BosqueLanguage
about: Regularized Programming

baseurl: ""
url: "https://bosque-lang.org"

allowsearch: true

disqus_shortname: 
google_analytics: 

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
